server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/230308-cms?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver